# Generated by Django 4.2.7 on 2023-11-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ArticuloenVenta',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoriaarticuloenventa',
        ),
    ]
