# Generated by Django 4.2.7 on 2023-11-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_post_articuloenventa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articuloenventa',
            options={'verbose_name': 'articulo', 'verbose_name_plural': 'articulos'},
        ),
        migrations.RenameField(
            model_name='articuloenventa',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='articuloenventa',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='articuloenventa',
            name='categorias',
        ),
        migrations.AddField(
            model_name='articuloenventa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaarticuloenventa'),
        ),
    ]
