# Generated by Django 4.2.7 on 2023-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_articuloenventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloenventa',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='articuloenventa',
            name='descripcion',
            field=models.TextField(max_length=50, verbose_name='descripcion:'),
        ),
        migrations.AlterField(
            model_name='articuloenventa',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='articulo:'),
        ),
    ]
