# Generated by Django 4.2.7 on 2023-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_articuloenventa_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloenventa',
            name='descripcion',
            field=models.TextField(max_length=5000, verbose_name='descripcion:'),
        ),
        migrations.AlterField(
            model_name='articuloenventa',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/tienda'),
        ),
    ]
