# Generated by Django 4.2.7 on 2023-12-15 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_alter_articulodisponible_ean13_and_more'),
        ('tienda', '0007_alter_producto_created_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated',
        ),
        migrations.AddField(
            model_name='producto',
            name='articulodisponible_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proveedores.articulodisponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='pvp',
            field=models.FloatField(default=0.0, verbose_name='Precio'),
        ),
    ]
