# Generated by Django 4.2.7 on 2023-12-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_alter_articulodisponible_ean13_and_more'),
        ('pedidos', '0003_alter_pedido_options'),
        ('tienda', '0009_alter_producto_pvp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proveedores.articulodisponible',),
        ),
    ]
