# Generated by Django 4.2.7 on 2023-12-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_alter_articulodisponible_ean13_and_more'),
        ('tienda', '0010_delete_producto_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('articulodisponible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proveedores.articulodisponible')),
            ],
            bases=('proveedores.articulodisponible',),
        ),
    ]
