# Generated by Django 4.2.7 on 2023-12-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_lineapedido_producto'),
        ('tienda', '0011_delete_producto_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaProd',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
