# Generated by Django 4.2.7 on 2023-12-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
