# Generated by Django 4.2.7 on 2023-12-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_delete_producto_producto'),
        ('pedidos', '0003_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='LineaPedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
