# Generated by Django 4.2.7 on 2023-12-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_remove_articulodisponible_altura_and_more'),
        ('pedidos', '0004_alter_lineapedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.articulodisponible'),
        ),
    ]
