# Generated by Django 4.2.7 on 2023-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulotienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=50, verbose_name='Creado el:')),
                ('updated', models.CharField(max_length=50, null=True, verbose_name='Actualizado el:')),
            ],
            options={
                'verbose_name': 'ctegoria tienda',
                'verbose_name_plural': 'categorias tienda',
            },
        ),
        migrations.CreateModel(
            name='CategoriaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.CharField(max_length=50, verbose_name='Creado el:')),
                ('updated', models.CharField(max_length=50, null=True, verbose_name='Actualizado el:')),
            ],
            options={
                'verbose_name': 'ctegoria tienda',
                'verbose_name_plural': 'categorias tienda',
            },
        ),
    ]
