# Generated by Django 4.2.7 on 2023-11-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_contenido_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título:'),
        ),
    ]
