# Generated by Django 4.2.7 on 2023-11-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('atributo1', models.CharField(max_length=50, verbose_name='Atributo 1')),
                ('atributo2', models.CharField(max_length=50, verbose_name='Atributo 2')),
                ('valor1', models.CharField(max_length=50, verbose_name=' Valos 1')),
                ('valor2', models.CharField(max_length=50, verbose_name='Valor 2')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('feature', models.CharField(max_length=50, verbose_name='Feature')),
                ('precioMercado', models.FloatField(verbose_name='Precio de Mercado')),
                ('pvpBigbuy', models.FloatField(verbose_name='PVP venta al publico en Bigbuy')),
                ('pvd', models.FloatField(verbose_name='Precio en Origen')),
                ('iva', models.FloatField(verbose_name='I.V.A.')),
                ('video', models.FloatField(verbose_name='Video')),
                ('ean13', models.CharField(max_length=50, verbose_name='ean')),
                ('ancho', models.URLField(max_length=500, verbose_name='Ancho')),
                ('altura', models.URLField(max_length=500, verbose_name='Alto')),
                ('profundidad', models.URLField(max_length=500, verbose_name='Profundo')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen1', models.URLField(max_length=500, verbose_name='Imágen')),
                ('imagen2', models.URLField(max_length=500, verbose_name='Imágen')),
                ('imagen3', models.URLField(max_length=500, verbose_name='Imágen')),
                ('imagen4', models.URLField(max_length=500, verbose_name='Imágen')),
                ('imagen5', models.URLField(max_length=500, verbose_name='Imágen')),
                ('imagen6', models.URLField(max_length=500, verbose_name='Imágen')),
                ('imagen7', models.URLField(max_length=500, verbose_name='Imágen')),
                ('imagen8', models.URLField(max_length=500, verbose_name='Imágen')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado:')),
                ('created', models.CharField(max_length=50, verbose_name='Creado el:')),
                ('updated', models.CharField(max_length=50, verbose_name='Actualizado el:')),
            ],
            options={
                'verbose_name': 'Articulo disponible para la venta en proveedores',
                'verbose_name_plural': 'Articulos disponibles para la venta en proveedores',
            },
        ),
    ]
