# Generated by Django 4.2.7 on 2023-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_articulodisponible_preciomercado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulodisponible',
            name='precioMercado',
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='inventariado',
            field=models.BooleanField(default=False, verbose_name='Inventariado'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='preciodemercado',
            field=models.FloatField(default=0, null=True, verbose_name='Precio de Mercado'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Alto'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='ancho',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='atributo1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atributo 1'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='atributo2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atributo 2'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='created',
            field=models.CharField(max_length=50, null=True, verbose_name='Creado el:'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='ean13',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ean'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='feature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen4',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen5',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen6',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen7',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='imagen8',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='iva',
            field=models.FloatField(blank=True, null=True, verbose_name='I.V.A.'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='profundidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Profundo'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='pvd',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio en Origen'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='updated',
            field=models.CharField(max_length=50, null=True, verbose_name='Actualizado el:'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='valor1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' Valor 1'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='valor2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor 2'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='video',
            field=models.FloatField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
