# Generated by Django 4.2.7 on 2023-11-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_remove_articulodisponible_preciomercado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulodisponible',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='atributo1',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='atributo2',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='imagen5',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='imagen6',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='imagen7',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='imagen8',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='profundidad',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='valor1',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='valor2',
        ),
        migrations.RemoveField(
            model_name='articulodisponible',
            name='video',
        ),
    ]
