# Generated by Django 4.2.7 on 2023-12-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_remove_articulodisponible_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulodisponible',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Alto'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='ancho',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='atributo1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atributo 1'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='atributo2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atributo 2'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado:'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='imagen2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='imagen3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='imagen4',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='imagen5',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='imagen6',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='imagen7',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='imagen8',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='profundidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Profundo'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='valor1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' Valor 1'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='valor2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor 2'),
        ),
        migrations.AddField(
            model_name='articulodisponible',
            name='video',
            field=models.FloatField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
