# Generated by Django 4.2.7 on 2023-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_remove_articulodisponible_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulodisponible',
            name='ean13',
            field=models.CharField(default=1, max_length=50, verbose_name='ean'),
            preserve_default=False,
        ),
    ]
