# Generated by Django 4.2.7 on 2023-12-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_alter_articulodisponible_ean13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulodisponible',
            name='pvpBigbuy',
            field=models.FloatField(default=0, verbose_name='PVP venta al publico en Bigbuy'),
        ),
    ]
