# Generated by Django 4.2.7 on 2023-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_alter_articulodisponible_pvpbigbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulodisponible',
            name='ean13',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ean'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='pvpBigbuy',
            field=models.FloatField(verbose_name='PVP venta al publico en Bigbuy'),
        ),
        migrations.AlterField(
            model_name='articulodisponible',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
