# Generated by Django 4.2.7 on 2023-12-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_articulodisponible_altura_articulodisponible_ancho_and_more'),
        ('proveedores', '0008_alter_articulodisponible_ean13_and_more'),
    ]

    operations = [
    ]
